name: Run Python Script

on:
  workflow_dispatch:

env:
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Load requirements
      run: pip install requirements
    - name: Run with MeitYQnA.py
      run: python MeitYQnA.py

